language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  global:
    - secure: "N/t4txw1k9bOUsLQWQOpzdJpMAdFFzzJqN2rWiijMJPEC9E1meoKMzFYr4kgNjInhVfkud8+3fOHZL/Ns4MLWexf1vsG1NFvrXSBuBD6MlPKYe77bb9WTmRvWfLSDg6F5BP/1uFjwebj4USN14RWlxyIgmsC1+bdCFVN2Wktg4k="
install:
  - pip install coveralls pytest requests six
script:
  - coverage run --source=chemspipy -m pytest
after_success:
  - coveralls
